language: php
php:
  - "7.2"
  - "7.1"
  - "7.0"
install:
  - composer install
  # Upgrade default Node.js version in Travis' PHP image from Node.js v0.10.x to 8.x
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.9/install.sh | bash;
  - source ~/.nvm/nvm.sh; nvm install 8
script:
  - composer test
after_success:
  - php vendor/bin/php-coveralls -v
notifications:
  irc:
    channels:
      - "chat.freenode.net#mediawiki-i18n"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
